version: '3.3'
services:
  RMI_SERVER:
    container_name: RMI_SERVER
    image: rmiserver:latest
    entrypoint: /bin/sh -c ./launchServer.sh
    environment:
      RMI_REMOTE_PORT: 1099
      RMI_REMOTE_HOST: RMI_SERVER
  RMI_HTTPPROXY:
    container_name: RMI_HTTPPROXY
    image: rmihttpproxy:latest
    entrypoint: /bin/sh -c ./launchServer.sh
    ports:
      - '80:80'
    environment:
      RMI_REMOTE_PORT: 1099
      RMI_REMOTE_HOST: RMI_SERVER
    depends_on:
      - RMI_SERVER
    links:
      - 'RMI_SERVER'
  RMI_CLIENT:
    container_name: RMI_CLIENT
    image: rmiclient:latest
    entrypoint: /bin/sh -c ./launchClient.sh
    environment:
      RMI_REMOTE_PORT: 1099
      RMI_REMOTE_HOST: RMI_HTTPPROXY
    depends_on:
      - RMI_HTTPPROXY
    links:
      - 'RMI_HTTPPROXY'
